name: Java CI with Gradle and Docker

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Verify Gradle artifacts
      - name: Verify build artifacts
        run: ls -R build/libs

      # Step 6: Debug Docker context
      - name: List workspace contents
        run: ls -R .

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:latest .

      # Step 9: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:latest

      # Step 10: Run Docker container
      - name: Run application
        run: docker run -d -p 8080:8080 SwaggerAPI
